### ISSUE TITLE
java 문법 enum 예시 코드 질문

### ISSUE THREAD

**Issue by rockpell** [jandy14/WEB-STUDY#2]
- [Java문법.md](https://github.com/jandy14/WEB-STUDY/blob/main/JAVA/Java%EB%AC%B8%EB%B2%95.md#enum) 에서 enum에 대한 예시 코드 중에 `enum Company`은 사용 예시가 없는 거 같은데 `enum Fruit`과 같은 방식 외에도 사용 할 수 있다는 것을 보여주기 위해 넣은 것인지 궁금합니다.

**Comment by jandy14** [comment]
코드는 참고자료에 있는 [생활코딩](https://opentutorials.org/course/1223/6062)에 `상수와 enum`파트에서 가져왔습니다.

코드의 의도는 `Company`에 `Apple`이란 열거값이 있지만 `Fruit`의 `Apple`에는 영향을 주지 않고 실행된다는 의미로 추가된 것입니다.

**Comment by jandy14** [comment]
충분한 답변이라 생각하고 이슈는 닫겠습니다.
