### ISSUE TITLE
[GraphQL] WSL2 Ubuntu 20.04 LTS 버전에서 진행 시 오류 발생

### ISSUE THREAD

**Issue by JIIIIIND** [jandy14/WEB-STUDY#4]
1. 버전 호환되지 않음
 -> WSL2에서 Node설치 시 10.19.0 버전으로 설치되며, 실행 시 nodes.flatMap이 없다는 오류 발생
 -> apollo-server 3버전으로 설치 필요(2버전에서 진행 시 'Error: Must provide Document' 오류 발생
2. fs, path 추가 관련 문제
 -> import 방식 사용 시 오류 발생, 'const fs = require('fs')와 같은 방식 사용
3. path 경로 오류 발생함
 -> path.join(...) 부분의 경로가 './src/schema.graphql'로 적혀있지만, 실행 시 src/src/schema.graphql을 읽으려고 함

**Comment by jandy14** [comment]
1번은 노드버전 차이로 생기는 이슈일거 같습니다. 노드버전을 14이상으로 하라고 명시해두겠습니다.

2번도 비슷한 이슈로 보입니다. import문법은 es6문법으로 13이상에서 사용가능하다고 하네요. 그래도 문법 통일을 위해서 require로 수정해두겠습니다.

3번은 노드 실행 위치를 프로젝트 폴더가 아닌 `src` 폴더 안에서 `node index.js`로 실행하신거 같습니다. 프로젝트 폴더에서 `node src/index.js`로 실행해보시고 문제가 계속되면 공유해주세요.
